# TEST CODE CONSTANTS (tests use 'american' morse)
HELLO = ". . . .   .   ---   ---   .  ."
EXCUSE_ME = ".   . - . .   . .  .   . . -   . . .   .       - -   ."
GOT_IT = "- - .   .  .   -       . .   -"
YOUR_WELCOME = ". .  . .   .  .   . . -   .  . .       . - -   .   ---   . .  .   .  .   - -   ."
NEED_MEDIC = "- .   .   .   - . .       - -   .   - . .   . .   . .  ."
REPEAT = ".  . .   .   . . . . .   .   . -   -"
OVER = ".  .   . . . -   .   .  . ."
OUT = ".  .   . . -   -"
ASSIST = ". -   . . .   . . .   . .   . . .   -"
CEASE_FIRE = ". .  .   .   . -   . . .   .       . - .   . .   .  . .   ."
COPY = ". .  .   .  .   . . . . .   . .  . ."
EASY_MONEY = ".   . -   . . .   . .  . .       - -   .  .   - .   .   . .  . ."
SIX_O_CLOCK = ". . .   . .   . - . .       .  .       . .  .   ---   .  .   . .  .   - . -"
TWELVE_O_CLOCK = "-   . - -   .   ---   . . . -   .       .  .       . .  .   ---   .  .   . .  .   - . -"